// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdo8AApDxkLxyN4wsahVsP4a-OWjkTTRg',
    appId: '1:772429300693:web:ee58d27cfebcc31608f35c',
    messagingSenderId: '772429300693',
    projectId: 'sp10-edc38',
    authDomain: 'sp10-edc38.firebaseapp.com',
    storageBucket: 'sp10-edc38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF8pAJOybESeHG-UL4-LgagVpe7_E44Zs',
    appId: '1:772429300693:android:9679f2018fe6056f08f35c',
    messagingSenderId: '772429300693',
    projectId: 'sp10-edc38',
    storageBucket: 'sp10-edc38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEkXvJyZk2DLCmfhnJExDi51dCWaSpdf4',
    appId: '1:772429300693:ios:659b2ad92f39f52608f35c',
    messagingSenderId: '772429300693',
    projectId: 'sp10-edc38',
    storageBucket: 'sp10-edc38.firebasestorage.app',
    iosBundleId: 'com.example.rapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEkXvJyZk2DLCmfhnJExDi51dCWaSpdf4',
    appId: '1:772429300693:ios:659b2ad92f39f52608f35c',
    messagingSenderId: '772429300693',
    projectId: 'sp10-edc38',
    storageBucket: 'sp10-edc38.firebasestorage.app',
    iosBundleId: 'com.example.rapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdo8AApDxkLxyN4wsahVsP4a-OWjkTTRg',
    appId: '1:772429300693:web:59a2086332629d2d08f35c',
    messagingSenderId: '772429300693',
    projectId: 'sp10-edc38',
    authDomain: 'sp10-edc38.firebaseapp.com',
    storageBucket: 'sp10-edc38.firebasestorage.app',
  );
}
